# Generated by Django 5.2.17 on 2026-08-21 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0002_department_departmentcontainerpage_department'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '指南类别',
                'verbose_name_plural': '指南类别',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GuidePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('location', models.CharField(max_length=200, verbose_name='地点')),
                ('opening_hours', models.TextField(verbose_name='开放时间')),
                ('contact', models.TextField(verbose_name='联系方式')),
                ('extra_notes', models.TextField(blank=True, verbose_name='补充说明')),
                ('responsible_party', models.CharField(max_length=200, verbose_name='责任来源或责任单位')),
                ('maintenance_mode', models.CharField(choices=[('self', '责任部门后台自维护'), ('curated', '统一邮箱投稿·总管理员代维护')], max_length=20, verbose_name='维护方式')),
                ('last_confirmed_on', models.DateField(verbose_name='最后确认日期或更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guides.guidecategory', verbose_name='指南类别')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departments.department', verbose_name='发布部门')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
