# Generated by Django 5.2.17 on 2026-08-28 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guidepage',
            options={'verbose_name': '校园指南页', 'verbose_name_plural': '校园指南页'},
        ),
    ]
