# Generated by Django 5.2.17 on 2026-08-21 05:18

import django.db.models.deletion
import modelcluster.fields
import notices.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0002_department_departmentcontainerpage_department'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': '受控标签',
                'verbose_name_plural': '受控标签',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ArticlePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('event_start_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('event_end_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('event_location', models.CharField(blank=True, max_length=200, verbose_name='活动地点')),
                ('event_is_online', models.BooleanField(default=False, verbose_name='线上活动')),
                ('event_registration_url', models.URLField(blank=True, verbose_name='报名链接')),
                ('summary', models.TextField(verbose_name='摘要')),
                ('body', wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('image', 4), ('attachment', 5), ('table', 6), ('external_link', 9)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': '标题文字'}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2（次级标题）'), ('h3', 'H3（三级标题）')], 'label': '级别'}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1)]], {}), 3: ('notices.blocks.ParagraphBlock', (), {}), 4: ('notices.blocks.ImageBlock', (), {}), 5: ('notices.blocks.AttachmentBlock', (), {}), 6: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': '表格'}), 7: ('wagtail.blocks.URLBlock', (), {'label': '链接地址'}), 8: ('wagtail.blocks.CharBlock', (), {'label': '链接文字'}), 9: ('wagtail.blocks.StructBlock', [[('url', 7), ('link_text', 8)]], {})})),
                ('external_url', models.URLField(blank=True, verbose_name='外部链接')),
                ('attachments', modelcluster.fields.ParentalManyToManyField(blank=True, to='wagtaildocs.document', verbose_name='附件')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departments.department', verbose_name='发布部门')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image', verbose_name='图片')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='NoticePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('event_start_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('event_end_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('event_location', models.CharField(blank=True, max_length=200, verbose_name='活动地点')),
                ('event_is_online', models.BooleanField(default=False, verbose_name='线上活动')),
                ('event_registration_url', models.URLField(blank=True, verbose_name='报名链接')),
                ('summary', models.TextField(verbose_name='摘要')),
                ('body', wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('image', 4), ('attachment', 5), ('table', 6), ('external_link', 9)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': '标题文字'}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2（次级标题）'), ('h3', 'H3（三级标题）')], 'label': '级别'}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1)]], {}), 3: ('notices.blocks.ParagraphBlock', (), {}), 4: ('notices.blocks.ImageBlock', (), {}), 5: ('notices.blocks.AttachmentBlock', (), {}), 6: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': '表格'}), 7: ('wagtail.blocks.URLBlock', (), {'label': '链接地址'}), 8: ('wagtail.blocks.CharBlock', (), {'label': '链接文字'}), 9: ('wagtail.blocks.StructBlock', [[('url', 7), ('link_text', 8)]], {})})),
                ('external_url', models.URLField(blank=True, verbose_name='外部链接')),
                ('attachments', modelcluster.fields.ParentalManyToManyField(blank=True, to='wagtaildocs.document', verbose_name='附件')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departments.department', verbose_name='发布部门')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image', verbose_name='图片')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='NoticeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='notices.noticepage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_tags', to='notices.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='noticepage',
            name='tags',
            field=notices.models.ControlledTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='notices.NoticeTag', to='notices.Tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='notices.articlepage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_tags', to='notices.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='articlepage',
            name='tags',
            field=notices.models.ControlledTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='notices.ArticleTag', to='notices.Tag', verbose_name='Tags'),
        ),
    ]
