# Generated by Django 5.2.17 on 2026-08-28 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlepage',
            options={'verbose_name': '文章页', 'verbose_name_plural': '文章页'},
        ),
        migrations.AlterModelOptions(
            name='noticepage',
            options={'verbose_name': '通知页', 'verbose_name_plural': '通知页'},
        ),
    ]
