# Generated by Django 5.2.17 on 2026-09-01 06:11

import peiligo.link_validation
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_alter_articlepage_body_alter_noticepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('image', 4), ('attachment', 5), ('table', 6), ('external_link', 9)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': '标题文字'}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2（次级标题）'), ('h3', 'H3（三级标题）')], 'label': '级别'}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1)]], {}), 3: ('notices.blocks.ParagraphBlock', (), {}), 4: ('notices.blocks.ImageBlock', (), {}), 5: ('notices.blocks.AttachmentBlock', (), {}), 6: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': '表格'}), 7: ('wagtail.blocks.URLBlock', (), {'label': '链接地址', 'validators': [peiligo.link_validation.validate_external_url]}), 8: ('wagtail.blocks.CharBlock', (), {'label': '链接文字'}), 9: ('wagtail.blocks.StructBlock', [[('url', 7), ('link_text', 8)]], {})}, verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='external_url',
            field=models.URLField(blank=True, validators=[peiligo.link_validation.validate_external_url], verbose_name='外部链接'),
        ),
        migrations.AlterField(
            model_name='noticepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('image', 4), ('attachment', 5), ('table', 6), ('external_link', 9)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': '标题文字'}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2（次级标题）'), ('h3', 'H3（三级标题）')], 'label': '级别'}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1)]], {}), 3: ('notices.blocks.ParagraphBlock', (), {}), 4: ('notices.blocks.ImageBlock', (), {}), 5: ('notices.blocks.AttachmentBlock', (), {}), 6: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': '表格'}), 7: ('wagtail.blocks.URLBlock', (), {'label': '链接地址', 'validators': [peiligo.link_validation.validate_external_url]}), 8: ('wagtail.blocks.CharBlock', (), {'label': '链接文字'}), 9: ('wagtail.blocks.StructBlock', [[('url', 7), ('link_text', 8)]], {})}, verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='noticepage',
            name='external_url',
            field=models.URLField(blank=True, validators=[peiligo.link_validation.validate_external_url], verbose_name='外部链接'),
        ),
    ]
