# Generated by Django 5.2.17 on 2026-09-10 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0005_articlepage_noindex_noticepage_noindex'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='cover_image',
            field=models.ForeignKey(blank=True, help_text='推荐尺寸 1600×600（8:3）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='轮播封面图'),
        ),
        migrations.AddField(
            model_name='noticepage',
            name='cover_image',
            field=models.ForeignKey(blank=True, help_text='推荐尺寸 1600×600（8:3）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='轮播封面图'),
        ),
    ]
