# Generated by Django 5.2.17 on 2026-08-21 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_title_zh'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(verbose_name='开始时间')),
                ('end_at', models.DateTimeField(verbose_name='结束时间')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.page', verbose_name='指向内容')),
            ],
            options={
                'verbose_name': '首页推荐位',
                'verbose_name_plural': '首页推荐位',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_text', models.TextField(blank=True, help_text='空＝无提示不展示（首页层 1，IA §7.1）', verbose_name='紧急提示文案')),
                ('alert_start_at', models.DateTimeField(blank=True, null=True, verbose_name='紧急提示起')),
                ('alert_end_at', models.DateTimeField(blank=True, null=True, verbose_name='紧急提示止')),
                ('feedback_email', models.EmailField(help_text='每页反馈链接（自动带内容标题与页面地址）与指南投稿邮箱同源单值', max_length=254, verbose_name='统一反馈邮箱')),
                ('redirect_notice_text', models.TextField(blank=True, help_text='空＝仅渲染 §11.4 四要素结构化信息（域名/来源/时间/变化声明）', verbose_name='跳转页声明文案')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
