# Generated by Django 5.2.17 on 2026-08-28 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_featureditem_sitesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': '首页', 'verbose_name_plural': '首页'},
        ),
        migrations.AlterModelOptions(
            name='sectionpage',
            options={'verbose_name': '板块页', 'verbose_name_plural': '板块页'},
        ),
    ]
