# Generated by Django 5.2.17 on 2026-09-01 06:30

import django.utils.timezone
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_homepage_options_alter_sectionpage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureditem',
            name='end_at',
            field=models.DateTimeField(default=home.models._featured_default_end, help_text='默认自开始时刻起 30 天，可编辑延长；提前撤下请关闭「启用」', verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='featureditem',
            name='start_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间'),
        ),
    ]
