# Generated by Django 5.2.17 on 2026-09-10 06:10

import django.db.models.deletion
import peiligo.link_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_featureditem_end_at_and_more'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_url', models.URLField(blank=True, validators=[peiligo.link_validation.validate_external_url], verbose_name='外部链接')),
                ('external_title', models.CharField(blank=True, max_length=255, verbose_name='外链标题')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('external_cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='外链封面图')),
                ('internal_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page', verbose_name='站内内容页')),
            ],
            options={
                'verbose_name': '首页轮播项',
                'verbose_name_plural': '首页轮播项',
                'ordering': ('sort_order', 'pk'),
            },
        ),
    ]
