# Generated by Django 5.2.17 on 2026-09-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpsHeartbeat',
            fields=[
                ('kind', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='作业种类')),
                ('ok', models.BooleanField(default=False, verbose_name='最近一次是否成功')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='结果细节')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时刻')),
            ],
            options={
                'verbose_name': '作业心跳',
                'verbose_name_plural': '作业心跳',
            },
        ),
    ]
