# Generated by Django 5.2.17 on 2026-09-01 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordState',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='password_state', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('password_last_set', models.DateTimeField(blank=True, help_text='为空＝后台设置/重置后尚未改密（强制改密中）。', null=True, verbose_name='密码设定时刻')),
            ],
            options={
                'verbose_name': '密码状态',
                'verbose_name_plural': '密码状态',
            },
        ),
    ]
