# Generated by Django 5.2.17 on 2026-08-21 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='代号（URL 部门段）')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, help_text='停用（取消勾选）即退出新建选择与筛选词表；既有内容保留部门名称', verbose_name='启用')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='departmentcontainerpage',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departments.department', verbose_name='部门'),
        ),
    ]
