# Generated by Django 5.2.17 on 2026-08-28 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_department_departmentcontainerpage_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentcontainerpage',
            options={'verbose_name': '部门容器', 'verbose_name_plural': '部门容器'},
        ),
    ]
