# Generated by Django 5.2.17 on 2026-08-21 05:18

import django.db.models.deletion
import modelcluster.fields
import notices.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0002_department_departmentcontainerpage_department'),
        ('notices', '0001_initial'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '学科·专业方向',
                'verbose_name_plural': '学科·专业方向',
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '资料类型',
                'verbose_name_plural': '资料类型',
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '适用平台',
                'verbose_name_plural': '适用平台',
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('summary', models.TextField(verbose_name='摘要')),
                ('body', wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('image', 4), ('attachment', 5), ('table', 6), ('external_link', 9)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': '标题文字'}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2（次级标题）'), ('h3', 'H3（三级标题）')], 'label': '级别'}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1)]], {}), 3: ('notices.blocks.ParagraphBlock', (), {}), 4: ('notices.blocks.ImageBlock', (), {}), 5: ('notices.blocks.AttachmentBlock', (), {}), 6: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': '表格'}), 7: ('wagtail.blocks.URLBlock', (), {'label': '链接地址'}), 8: ('wagtail.blocks.CharBlock', (), {'label': '链接文字'}), 9: ('wagtail.blocks.StructBlock', [[('url', 7), ('link_text', 8)]], {})})),
                ('external_url', models.URLField(blank=True, verbose_name='外部链接')),
                ('attachments', modelcluster.fields.ParentalManyToManyField(blank=True, to='wagtaildocs.document', verbose_name='附件')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departments.department', verbose_name='发布部门')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resources.discipline', verbose_name='学科·专业方向')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MaterialTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='resources.materialpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_tags', to='notices.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='materialpage',
            name='tags',
            field=notices.models.ControlledTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='resources.MaterialTag', to='notices.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='materialpage',
            name='material_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resources.materialtype', verbose_name='资料类型'),
        ),
        migrations.CreateModel(
            name='SoftwareToolPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('image', 4), ('table', 5), ('external_link', 8)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': '标题文字'}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2（次级标题）'), ('h3', 'H3（三级标题）')], 'label': '级别'}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1)]], {}), 3: ('notices.blocks.ParagraphBlock', (), {}), 4: ('notices.blocks.ImageBlock', (), {}), 5: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': '表格'}), 6: ('wagtail.blocks.URLBlock', (), {'label': '链接地址'}), 7: ('wagtail.blocks.CharBlock', (), {'label': '链接文字'}), 8: ('wagtail.blocks.StructBlock', [[('url', 6), ('link_text', 7)]], {})})),
                ('source_url', models.URLField(verbose_name='来源链接或第三方网盘链接')),
                ('license_note', models.TextField(verbose_name='授权或费用说明')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departments.department', verbose_name='发布部门')),
                ('platforms', modelcluster.fields.ParentalManyToManyField(to='resources.platform', verbose_name='适用平台')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
