# Generated by Django 5.2.17 on 2026-08-28 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialpage',
            options={'verbose_name': '学习资料页', 'verbose_name_plural': '学习资料页'},
        ),
        migrations.AlterModelOptions(
            name='softwaretoolpage',
            options={'verbose_name': '软件与工具页', 'verbose_name_plural': '软件与工具页'},
        ),
    ]
