# Generated by Django 5.2.17 on 2026-08-28 09:32

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_materialpage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('image', 4), ('attachment', 5), ('table', 6), ('external_link', 9)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': '标题文字'}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2（次级标题）'), ('h3', 'H3（三级标题）')], 'label': '级别'}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1)]], {}), 3: ('notices.blocks.ParagraphBlock', (), {}), 4: ('notices.blocks.ImageBlock', (), {}), 5: ('notices.blocks.AttachmentBlock', (), {}), 6: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': '表格'}), 7: ('wagtail.blocks.URLBlock', (), {'label': '链接地址'}), 8: ('wagtail.blocks.CharBlock', (), {'label': '链接文字'}), 9: ('wagtail.blocks.StructBlock', [[('url', 7), ('link_text', 8)]], {})}, verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='softwaretoolpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('image', 4), ('table', 5), ('external_link', 8)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': '标题文字'}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2（次级标题）'), ('h3', 'H3（三级标题）')], 'label': '级别'}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1)]], {}), 3: ('notices.blocks.ParagraphBlock', (), {}), 4: ('notices.blocks.ImageBlock', (), {}), 5: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': '表格'}), 6: ('wagtail.blocks.URLBlock', (), {'label': '链接地址'}), 7: ('wagtail.blocks.CharBlock', (), {'label': '链接文字'}), 8: ('wagtail.blocks.StructBlock', [[('url', 6), ('link_text', 7)]], {})}, verbose_name='正文'),
        ),
    ]
