# Generated by Django 5.2.17 on 2026-09-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_alter_materialpage_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialpage',
            name='noindex',
            field=models.BooleanField(default=False, help_text='勾选后本页输出 noindex 且不进入 sitemap.xml（IA §10 #7）', verbose_name='禁止搜索引擎收录'),
        ),
        migrations.AddField(
            model_name='softwaretoolpage',
            name='noindex',
            field=models.BooleanField(default=False, help_text='勾选后本页输出 noindex 且不进入 sitemap.xml（IA §10 #7）', verbose_name='禁止搜索引擎收录'),
        ),
    ]
