"""
Django settings for peiligo project.

Generated by 'wagtail start peiligo' (Wagtail 7.4.2 official template), then
adapted to the repo layout of docs/plans/03_DELIVERY_OPERATIONS_PLAN.md §2
(project package under src/, apps / templates / static at repo root).
Adapted lines are marked with "M1:" comments; everything else keeps the
official template defaults (ADR-0003 clean skeleton).

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import dj_database_url

# M1: src/ layout — PROJECT_DIR = src/peiligo, BASE_DIR = repo root.
PROJECT_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = PROJECT_DIR.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deploy/checklist/


# Application definition

INSTALLED_APPS = [
    "home",
    "search",
    # M1: 按 03 计划 §2 预置的空壳 app（无模型无代码，后续里程碑填充）
    "departments",
    "notices",
    "resources",
    "guides",
    "frontend",
    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    # A3.1（CONTENT_MODEL §13.4）：站点设置载体＝BaseSiteSetting 单例
    # （ADR-0005 载体表 #14）；编辑界面与前台消费由 contrib 提供。
    "wagtail.contrib.settings",
    # A3.1（CONTENT_MODEL §11.1 落位提示）：表格块官方实现
    # wagtail.contrib.table_block.TableBlock 随白名单启用。
    "wagtail.contrib.table_block",
    # M2.2（IA §10）：sitemap.xml 发射器；容器排除见 DepartmentContainerPage。
    # django.contrib.sitemaps 提供 sitemap 视图与内置 sitemap.xml 模板。
    "django.contrib.sitemaps",
    "wagtail.contrib.sitemaps",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtail",
    "modelcluster",
    "taggit",
    "django_filters",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # F-05（SB §10-1/SEC-01）：django-axes 登录限速——DB 存储处理器（无
    # Redis 依赖），非第二套认证系统（仅前置的失败计数后端＋中间件，
    # ModelBackend 仍为唯一凭据校验者）。app 置尾，迁移随 axes app 走。
    "axes",
    # F-07：应用日志微 app（信号接收器＋publish_scheduled 结果包装命令），
    # 零模型零迁移。
    "peiligo.applog",
    # F-08B（R-05 方案 B）：用户/组治理 DB 级审计——复用 Wagtail 官方
    # log_actions（ModelLogEntry＋LogContext），零自建模型零迁移。
    "peiligo.govaudit",
    # F-05R（SB §2.4）：强制改密闸门——后台设置/重置密码后必须先自行
    # 改密（单状态表＋服务端路由级中间件；非第二套认证系统）。
    "peiligo.passwordgate",
    # F-12：备份/恢复工程（backup_run/backup_prune/backup_restore 三命令，
    # 零模型零迁移）。
    "peiligo.backupkit",
    # F-13：监控信号（OpsHeartbeat 心跳表＋ops_report 快照命令，无平台无常驻）。
    "peiligo.opsignal",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    # F-05R（SB §2.4 ③）：已登录且密码未设定 → 服务端路由级强制改密。
    "peiligo.passwordgate.middleware.PasswordChangeGateMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "wagtail.contrib.redirects.middleware.RedirectMiddleware",
    # F-05：锁定态把 authenticate() 的 PermissionDenied 转为锁定响应。
    "axes.middleware.AxesMiddleware",
]

# F-05：AxesStandaloneBackend 置首（锁定判定与失败计数前置闸门），
# ModelBackend 仍为唯一凭据校验后端——零第二套认证系统。
AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesStandaloneBackend",
    "django.contrib.auth.backends.ModelBackend",
]

# F-05（SB §10-1 冻结值）：10 次失败 → 锁 15 分钟；成功登录即清零计数
# （AXES_RESET_ON_SUCCESS）。锁定键＝SB §2.3 建议的 username＋ip_address
# 组合（兼顾撞库与爆破；axes 8.3.1 缺省仅按 IP——校园 NAT 共享出口下
# 任一账号 10 次失败将误锁全站点，故显式钉值）；存储＝DB handler
# （axes_attempt 表，无 Redis 依赖）。
AXES_FAILURE_LIMIT = 10
AXES_COOLOFF_TIME = timedelta(minutes=15)
AXES_RESET_ON_SUCCESS = True
AXES_LOCKOUT_PARAMETERS = [["username", "ip_address"]]

# F-07（SB §6.2 / G2 缺口 23）：结构化 LOGGING——单行 JSON 入 stdout，
# 由运行环境采集（容器/宿主轮转负责保留期，工程默认 ≥30 天、与备份
# 保留对齐；零文件 handler、零外部日志框架）。logger 层级一律 ≥INFO
# （SB §6.2 #4：DEBUG 级不入生产管道）；错误可见性＝django.request/root
# 显式接线（含 exc 堆栈字段，仅入日志管道不入 HTTP 响应）。
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "json": {"()": "peiligo.logging_utils.JsonFormatter"},
    },
    "handlers": {
        "console_json": {
            "class": "logging.StreamHandler",
            "formatter": "json",
        },
    },
    "loggers": {
        # 应用事件（peiligo.applog 信号接收器经 peiligo.events 发出，层级
        # 命名天然归入本 logger）。
        "peiligo": {"handlers": ["console_json"], "level": "INFO", "propagate": False},
        "django": {"handlers": ["console_json"], "level": "INFO", "propagate": False},
        # 请求异常（应用错误可见性主通道）独立成行，不向 root 重复传播。
        "django.request": {"handlers": ["console_json"], "level": "ERROR", "propagate": False},
    },
    "root": {"handlers": ["console_json"], "level": "INFO"},
}

ROOT_URLCONF = "peiligo.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # M1: 模板目录位于仓库根 templates/（03 计划 §2）
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # M2.2（IA §6.1/§6.2）：全站页头/页脚固定清单（零页面树查询）
                "peiligo.context_processors.site_chrome",
            ],
        },
    },
]

WSGI_APPLICATION = "peiligo.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


def env_required(name: str) -> str:
    """A1.1（03 计划 S1）：连接与敏感配置一律环境变量外置，缺失即快速失败。

    哑值样例见 .env.example（复制为本地 .env 导出，.env 不入库）。
    """
    value = os.environ.get(name)
    if not value:
        raise RuntimeError(f"{name} 未设置：环境变量外置（03 计划 S1），哑值样例见 .env.example")
    return value


# A1.1（03 计划 S1）：本地与测试统一 PostgreSQL，连接全环境变量外置，
# SQLite 不再是基线；主机/端口/库名零硬编码（防旧审计 R5 硬编码模式复发）。
DATABASES = {"default": dj_database_url.parse(env_required("DATABASE_URL"))}

# A1.1（03 计划 S1）：独立测试库——库名取自 TEST_DATABASE_URL（环境变量），
# pytest-django 沿用该名创建/销毁测试库（不加 test_ 前缀）；未设置时回落
# Django 默认（test_ 前缀）。连接参数沿用 default：本地与测试同用同一 PG 实例。
if _test_database_url := os.environ.get("TEST_DATABASE_URL"):
    DATABASES["default"]["TEST"] = {
        "NAME": dj_database_url.parse(_test_database_url)["NAME"],
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        # F-05（SB §10-1 冻结值）：密码最短 12 位。
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {"min_length": 12},
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# F-05（SB §10-1）：会话有效期 24 小时（默认站点后台会话时长）。
SESSION_COOKIE_AGE = 60 * 60 * 24


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# M5.1（admin 中文化）：产品级简体中文——Django admin 与 Wagtail admin
# 均自带 zh_Hans 翻译（USE_I18N=True 前提下激活）；展示层口径，
# 非业务语义，零迁移。
LANGUAGE_CODE = "zh-hans"

# 业务时区＝钟面层口径（管理员输入/前台显示；PUBLISH_ARCHIVE_SCHEDULING
# §4.2/§4.4）：调度判定层为 aware 绝对时刻比较，不受本值影响；USE_TZ
# 保持 True（aware 不变式前提），非 DB schema 项、零迁移。
TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

# M1: 静态源目录位于仓库根 static/（03 计划 §2）
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# M1: collectstatic 输出目录独立于源目录 static/
STATIC_ROOT = BASE_DIR / "staticfiles"
STATIC_URL = "/static/"

# A1.1（03 计划 S1）：媒体根可外置（哑值样例见 .env.example）；未设置时默认仓库内 media/
MEDIA_ROOT = os.environ.get("MEDIA_ROOT") or (BASE_DIR / "media")
MEDIA_URL = "/media/"

# Default storage settings
# See https://docs.djangoproject.com/en/5.2/ref/settings/#std-setting-STORAGES
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Django sets a maximum of 1000 fields per form by default, but particularly complex page models
# can exceed this limit within Wagtail's page editor.
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10_000


# Wagtail settings

# AVR②（ADMIN_VISUAL_RECOVERY_CONTRACT §3）：品牌名统一为大小写规范的
# “Peiligo”（禁造中文品牌名）。该值同时供前台 site_brand 使用，故仅改
# 大小写；后台标题“Peiligo 内容管理”由 templates/wagtailadmin/home.html
# 覆盖承担，不在此塞中文。
WAGTAIL_SITE_NAME = "Peiligo"

# AVR②：Wagtail 7.4.2 zh_Hans 目录缺少的少量 admin 文案（定时发布弹窗、
# 锁定开关说明、“被引用 N 次”）经项目级目录覆盖补译（Django 官方
# LOCALE_PATHS 逐 msgid 合并，优先于应用内目录；见 locale/zh_Hans/）。
LOCALE_PATHS = [
    BASE_DIR / "locale",
]

# A3.1（CONTENT_MODEL §13）：受控 Snippet/设置模型默认主键取 BigAutoField
# （Django 官方推荐口径），消除 models.W042；不影响既有表与历史 migration。
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Search
# https://docs.wagtail.org/en/stable/topics/search/backends.html
# F-01（ADR-0006 · Accepted）：E1＝Wagtail DB 后端 icontains fallback。
# 显式后端选择＝E1 生产落地前提（PRODUCTION_IMPLEMENTATION_REQUIRED=YES）：
# 通用 database 后端按连接 vendor 分派，PostgreSQL 下走 FTS＝E2 语义；
# 此处固定指向项目内 fallback 子类，任何 vendor 下均为 icontains 语义。
# 既有边界（CM §20.2，选型已接受）：RelatedFields 文本缺席、boost 忽略、
# 无相关度排序——保序由 services 层 order_by_relevance=False 统一施加。
WAGTAILSEARCH_BACKENDS = {
    "default": {
        "BACKEND": "search.backends.E1IcontainsSearchBackend",
    }
}

# Base URL to use when referring to full URLs within the Wagtail admin backend -
# e.g. in notification emails. Don't include '/admin' or a trailing slash
# 终审 L-1：生产经环境外置（production.py env_required，与部署域名同源
# 配置）；此处的哑值仅供本地/测试 settings 导入面使用。
WAGTAILADMIN_BASE_URL = "http://example.com"

# Allowed file extensions for documents in the document library.
# This can be omitted to allow all files, but note that this may present a security risk
# if untrusted users are allowed to upload files -
# see https://docs.wagtail.org/en/stable/advanced_topics/deploying.html#user-uploaded-files
# F-02（SECURITY_BASELINE §4.1 人工冻结清单）：wagtaildocs 面扩展名白名单。
# 图片格式（png/jpg/webp）走 wagtailimages（Pillow/Willow 解码校验），不在此。
# 扩展名仅是第一层；声明 MIME/内容签名一致性收口见 peiligo.upload_validation
# （下一设置项），三级一致性回归见 tests/test_upload_validation.py。
WAGTAILDOCS_EXTENSIONS = ["doc", "docx", "pdf", "ppt", "pptx", "xls", "xlsx"]

# F-02（SEC-17 图片面收口；SB §4.1 冻结白名单图片项＝png/jpg/webp）：
# Wagtail 缺省另放行 avif/gif，超出冻结集，故显式钉值收窄。jpeg 为 jpg
# 同格式别名（PRD 白名单按格式口径，接受 .jpeg 文件名，非格式扩充）。
WAGTAILIMAGES_EXTENSIONS = ["jpg", "jpeg", "png", "webp"]

# F-02（SECURITY_BASELINE §13 / G2 Q1 人工冻结值）：20 MiB 硬上限，不由
# 代码侧调整。
WAGTAILDOCS_MAX_UPLOAD_SIZE = 20 * 1024 * 1024  # 20MB

# F-02：上传表单统一收口——单文件/多文件/编辑替换三条后台路径均经
# get_document_form 构建（官方 WAGTAILDOCS_DOCUMENT_FORM_BASE 覆盖点），
# 文件名治理＋声明 MIME＋内容签名三级一致性见 peiligo/upload_validation.py。
WAGTAILDOCS_DOCUMENT_FORM_BASE = "peiligo.upload_validation.ValidatedDocumentForm"

# M2.2（IA §6.1 页脚反馈）：统一反馈工作邮箱，环境变量外置（哑值样例见
# .env.example）。正式载体为站点级配置 SiteSettings.feedback_email（终审
# M-1：前台取值站点设置优先、本值仅兜底，见 peiligo.context_processors）；
# ``or`` 缺省——环境置空串视同未设，避免兜底被空值打穿。
FEEDBACK_EMAIL = os.environ.get("FEEDBACK_EMAIL") or "feedback@example.com"
