"""
Django settings for peiligo project.

Generated by 'wagtail start peiligo' (Wagtail 7.4.2 official template), then
adapted to the repo layout of docs/plans/03_DELIVERY_OPERATIONS_PLAN.md §2
(project package under src/, apps / templates / static at repo root).
Adapted lines are marked with "M1:" comments; everything else keeps the
official template defaults (ADR-0003 clean skeleton).

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url

# M1: src/ layout — PROJECT_DIR = src/peiligo, BASE_DIR = repo root.
PROJECT_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = PROJECT_DIR.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deploy/checklist/


# Application definition

INSTALLED_APPS = [
    "home",
    "search",
    # M1: 按 03 计划 §2 预置的空壳 app（无模型无代码，后续里程碑填充）
    "departments",
    "notices",
    "resources",
    "guides",
    "frontend",
    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    # A3.1（CONTENT_MODEL §13.4）：站点设置载体＝BaseSiteSetting 单例
    # （ADR-0005 载体表 #14）；编辑界面与前台消费由 contrib 提供。
    "wagtail.contrib.settings",
    # A3.1（CONTENT_MODEL §11.1 落位提示）：表格块官方实现
    # wagtail.contrib.table_block.TableBlock 随白名单启用。
    "wagtail.contrib.table_block",
    # M2.2（IA §10）：sitemap.xml 发射器；容器排除见 DepartmentContainerPage。
    # django.contrib.sitemaps 提供 sitemap 视图与内置 sitemap.xml 模板。
    "django.contrib.sitemaps",
    "wagtail.contrib.sitemaps",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtail",
    "modelcluster",
    "taggit",
    "django_filters",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "wagtail.contrib.redirects.middleware.RedirectMiddleware",
]

ROOT_URLCONF = "peiligo.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # M1: 模板目录位于仓库根 templates/（03 计划 §2）
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # M2.2（IA §6.1/§6.2）：全站页头/页脚固定清单（零页面树查询）
                "peiligo.context_processors.site_chrome",
            ],
        },
    },
]

WSGI_APPLICATION = "peiligo.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


def env_required(name: str) -> str:
    """A1.1（03 计划 S1）：连接与敏感配置一律环境变量外置，缺失即快速失败。

    哑值样例见 .env.example（复制为本地 .env 导出，.env 不入库）。
    """
    value = os.environ.get(name)
    if not value:
        raise RuntimeError(f"{name} 未设置：环境变量外置（03 计划 S1），哑值样例见 .env.example")
    return value


# A1.1（03 计划 S1）：本地与测试统一 PostgreSQL，连接全环境变量外置，
# SQLite 不再是基线；主机/端口/库名零硬编码（防旧审计 R5 硬编码模式复发）。
DATABASES = {"default": dj_database_url.parse(env_required("DATABASE_URL"))}

# A1.1（03 计划 S1）：独立测试库——库名取自 TEST_DATABASE_URL（环境变量），
# pytest-django 沿用该名创建/销毁测试库（不加 test_ 前缀）；未设置时回落
# Django 默认（test_ 前缀）。连接参数沿用 default：本地与测试同用同一 PG 实例。
if _test_database_url := os.environ.get("TEST_DATABASE_URL"):
    DATABASES["default"]["TEST"] = {
        "NAME": dj_database_url.parse(_test_database_url)["NAME"],
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# M5.1（admin 中文化）：产品级简体中文——Django admin 与 Wagtail admin
# 均自带 zh_Hans 翻译（USE_I18N=True 前提下激活）；展示层口径，
# 非业务语义，零迁移。
LANGUAGE_CODE = "zh-hans"

# 业务时区＝钟面层口径（管理员输入/前台显示；PUBLISH_ARCHIVE_SCHEDULING
# §4.2/§4.4）：调度判定层为 aware 绝对时刻比较，不受本值影响；USE_TZ
# 保持 True（aware 不变式前提），非 DB schema 项、零迁移。
TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

# M1: 静态源目录位于仓库根 static/（03 计划 §2）
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# M1: collectstatic 输出目录独立于源目录 static/
STATIC_ROOT = BASE_DIR / "staticfiles"
STATIC_URL = "/static/"

# A1.1（03 计划 S1）：媒体根可外置（哑值样例见 .env.example）；未设置时默认仓库内 media/
MEDIA_ROOT = os.environ.get("MEDIA_ROOT") or (BASE_DIR / "media")
MEDIA_URL = "/media/"

# Default storage settings
# See https://docs.djangoproject.com/en/5.2/ref/settings/#std-setting-STORAGES
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Django sets a maximum of 1000 fields per form by default, but particularly complex page models
# can exceed this limit within Wagtail's page editor.
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10_000


# Wagtail settings

# AVR②（ADMIN_VISUAL_RECOVERY_CONTRACT §3）：品牌名统一为大小写规范的
# “Peiligo”（禁造中文品牌名）。该值同时供前台 site_brand 使用，故仅改
# 大小写；后台标题“Peiligo 内容管理”由 templates/wagtailadmin/home.html
# 覆盖承担，不在此塞中文。
WAGTAIL_SITE_NAME = "Peiligo"

# AVR②：Wagtail 7.4.2 zh_Hans 目录缺少的少量 admin 文案（定时发布弹窗、
# 锁定开关说明、“被引用 N 次”）经项目级目录覆盖补译（Django 官方
# LOCALE_PATHS 逐 msgid 合并，优先于应用内目录；见 locale/zh_Hans/）。
LOCALE_PATHS = [
    BASE_DIR / "locale",
]

# A3.1（CONTENT_MODEL §13）：受控 Snippet/设置模型默认主键取 BigAutoField
# （Django 官方推荐口径），消除 models.W042；不影响既有表与历史 migration。
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Search
# https://docs.wagtail.org/en/stable/topics/search/backends.html
WAGTAILSEARCH_BACKENDS = {
    "default": {
        "BACKEND": "wagtail.search.backends.database",
    }
}

# Base URL to use when referring to full URLs within the Wagtail admin backend -
# e.g. in notification emails. Don't include '/admin' or a trailing slash
WAGTAILADMIN_BASE_URL = "http://example.com"

# Allowed file extensions for documents in the document library.
# This can be omitted to allow all files, but note that this may present a security risk
# if untrusted users are allowed to upload files -
# see https://docs.wagtail.org/en/stable/advanced_topics/deploying.html#user-uploaded-files
WAGTAILDOCS_EXTENSIONS = [
    "csv",
    "docx",
    "key",
    "odt",
    "pdf",
    "pptx",
    "rtf",
    "txt",
    "xlsx",
    "zip",
]

# Maximum upload size for documents in bytes.
WAGTAILDOCS_MAX_UPLOAD_SIZE = 10 * 1024 * 1024  # 10MB

# M2.2（IA §6.1 页脚反馈）：统一反馈工作邮箱，环境变量外置（哑值样例见
# .env.example）。正式载体为站点级配置（ADR-0005 载体表 #14，M3+ 终判），
# 此前以 settings 过渡承载，不建模型、不伪造站点配置数据。
FEEDBACK_EMAIL = os.environ.get("FEEDBACK_EMAIL", "feedback@example.com")
